import React, { useContext, useState } from 'react';
import { useSettingsStore } from '../../store';
import { WorkspaceMode } from '../../constants';
import SectionShell, { SettingsLayoutContext } from './SectionShell';

const MODE_COPY: Record<WorkspaceMode, { title: string; description: string }> = {
  local: {
    title: 'Local',
    description: 'Bring your own chat model — Ollama, OpenAI, Claude, Gemini, anything OpenAI-compatible. No account needed.',
  },
  remote: {
    title: 'Remote',
    description: "WorkspaceGPT's managed model. Sign in once; no model keys to supply.",
  },
};

/**
 * The single mode switch at the top of Settings. It decides one thing: where
 * chat inference comes from — the user's own provider, or WorkspaceGPT's
 * managed endpoint. Which sections render (model picker vs account card)
 * follows from it; see `config.mode` in settingsStore.
 *
 * It deliberately does NOT move the index. Embeddings and the vector store are
 * always local (getEmbeddingSettings / getVectorStoreSettings), so switching
 * modes never invalidates an index and never needs a re-sync.
 */
const ModeSelector: React.FC = () => {
  const { config, setMode } = useSettingsStore();
  const mode = config.mode;
  const [pendingMode, setPendingMode] = useState<WorkspaceMode | null>(null);

  const syncBusy =
    !!config.confluence?.isSyncing ||
    !!config.confluence?.isIndexing ||
    !!config.ado?.isSyncing ||
    !!config.ado?.isIndexing;

  const requestSwitch = (next: WorkspaceMode) => {
    if (next === mode || syncBusy) return;
    setPendingMode(next);
  };

  const confirmSwitch = () => {
    if (pendingMode) setMode(pendingMode);
    setPendingMode(null);
  };

  // A workspace with nothing connected yet is still being set up, and mode is
  // the first decision — show it expanded. Once a source is connected, the
  // switch is rarely touched and collapses to its one-word summary.
  const isFreshInstall =
    !config.confluence?.isAuthenticated && !config.ado?.isAuthenticated;

  // With a whole page to itself (desktop), the choice reads better as two
  // cards that each say what they mean than as a two-word segmented control.
  const { layout } = useContext(SettingsLayoutContext);
  const modeCards = (
    <div className='mode-cards' role='radiogroup' aria-label='Mode'>
      {(Object.keys(MODE_COPY) as WorkspaceMode[]).map((m) => (
        <button
          type='button'
          key={m}
          role='radio'
          aria-checked={mode === m}
          className={`mode-card${mode === m ? ' mode-card--active' : ''}`}
          onClick={() => requestSwitch(m)}
          disabled={syncBusy && mode !== m}
          data-tooltip={syncBusy && mode !== m ? 'Wait for the current sync to finish' : undefined}
        >
          <span className='mode-card-title'>
            {MODE_COPY[m].title}
            {mode === m && <span className='mode-card-current'>Current</span>}
          </span>
          <span className='mode-card-desc'>{MODE_COPY[m].description}</span>
        </button>
      ))}
    </div>
  );

  return (
    <SectionShell
      storageKey='mode'
      title='Mode'
      summary={MODE_COPY[mode].title}
      defaultOpen={isFreshInstall}
    >
      <div className='settings-form'>
        {layout === 'page' ? modeCards : (
        <div className='mode-toggle' role='tablist'>
          {(Object.keys(MODE_COPY) as WorkspaceMode[]).map((m) => (
            <button
              type='button'
              key={m}
              role='tab'
              aria-selected={mode === m}
              className={`mode-toggle-option${mode === m ? ' mode-toggle-option--active' : ''}`}
              onClick={() => requestSwitch(m)}
              disabled={syncBusy && mode !== m}
              data-tooltip={syncBusy && mode !== m ? 'Wait for the current sync to finish' : undefined}
            >
              {MODE_COPY[m].title}
            </button>
          ))}
        </div>
        )}
        {layout !== 'page' && (
          <p className='description-text mode-toggle-desc'>{MODE_COPY[mode].description}</p>
        )}
      </div>

      {pendingMode && (
        <div className='mode-confirm-overlay' role='dialog' aria-modal='true'>
          <div className='mode-confirm-dialog'>
            <p>
              Switch to <strong>{MODE_COPY[pendingMode].title}</strong> mode?{' '}
              {pendingMode === 'remote'
                ? "Answers will be generated by WorkspaceGPT's managed model, which needs an account."
                : 'Answers will be generated by the chat model you configure yourself.'}{' '}
              Your indexed Confluence and Azure DevOps content stays exactly as it is.
            </p>
            <div className='mode-confirm-actions'>
              <button type='button' className='secondary-button' onClick={() => setPendingMode(null)}>
                Cancel
              </button>
              <button type='button' className='primary-button' onClick={confirmSwitch}>
                Switch
              </button>
            </div>
          </div>
        </div>
      )}
    </SectionShell>
  );
};

export default ModeSelector;
