/**
 * The Chrome extension is configured entirely from a "share code" generated by
 * the VS Code extension. The code is a base64-encoded bundle of the creator's
 * own credentials; Chrome stores them and talks directly to Gemini, Qdrant, and
 * the LLM. There is no server in between.
 *
 * Security note: the share code carries real API keys. Anyone with the code (or
 * access to this browser's storage) has those keys. It's meant for sharing to
 * your own browser / trusted people — treat it like a password.
 */
export interface ChromeSettings {
  qdrant: { url: string; apiKey: string; collectionPrefix?: string };
  /** All configured Gemini keys, tried in order with 429 failover. */
  gemini: { apiKeys: string[] };
  /** All configured chat-model keys, tried in order with 429 failover. */
  llm: { baseUrl: string; apiKeys: string[]; model: string };
}

/**
 * Versioned wire format of a share code (must match the VS Code producer).
 * v1 carried a single key per provider; v2 carries the full failover list.
 * Both are accepted on decode so an old share code still works.
 */
export interface ShareBundle {
  v: 1 | 2;
  qdrant: { url: string; apiKey?: string; collectionPrefix?: string };
  gemini: { apiKey?: string; apiKeys?: string[] };
  llm: { baseUrl: string; apiKey?: string; apiKeys?: string[]; model: string };
}

export const DEFAULT_SETTINGS: ChromeSettings = {
  qdrant: { url: '', apiKey: '', collectionPrefix: '' },
  gemini: { apiKeys: [] },
  llm: { baseUrl: '', apiKeys: [], model: '' },
};

const KEY = 'workspacegpt-settings';

/** Merge a legacy single key with a multi-key array, trimmed and de-duplicated. */
function normalizeApiKeys(apiKeys: unknown, legacy?: unknown): string[] {
  const arr = Array.isArray(apiKeys) ? apiKeys : [];
  const merged = [...arr, legacy].map((k) => (typeof k === 'string' ? k.trim() : '')).filter(Boolean);
  return [...new Set(merged)];
}

export async function loadSettings(): Promise<ChromeSettings> {
  const stored = await chrome.storage.local.get(KEY);
  const s = stored[KEY] ?? {};
  return {
    qdrant: { ...DEFAULT_SETTINGS.qdrant, ...(s.qdrant ?? {}) },
    gemini: { apiKeys: normalizeApiKeys(s.gemini?.apiKeys, s.gemini?.apiKey) },
    llm: {
      ...DEFAULT_SETTINGS.llm,
      ...(s.llm ?? {}),
      apiKeys: normalizeApiKeys(s.llm?.apiKeys, s.llm?.apiKey),
    },
  };
}

export async function saveSettings(settings: ChromeSettings): Promise<void> {
  await chrome.storage.local.set({ [KEY]: settings });
}

export function isConfigured(s: ChromeSettings): boolean {
  return !!(s.qdrant.url && s.gemini.apiKeys.length > 0 && s.llm.apiKeys.length > 0 && s.llm.baseUrl);
}

/**
 * Decode a share code into settings. Throws with a friendly message if the code
 * is malformed or an unsupported version.
 */
export function decodeShareCode(code: string): ChromeSettings {
  let bundle: ShareBundle;
  try {
    bundle = JSON.parse(atob(code.trim()));
  } catch {
    throw new Error('That share code is not valid. Copy it again from VS Code.');
  }
  const geminiKeys = normalizeApiKeys(bundle.gemini?.apiKeys, bundle.gemini?.apiKey);
  const llmKeys = normalizeApiKeys(bundle.llm?.apiKeys, bundle.llm?.apiKey);
  if ((bundle.v !== 1 && bundle.v !== 2) || !bundle.qdrant?.url || geminiKeys.length === 0 || llmKeys.length === 0) {
    throw new Error('That share code is missing required fields or is an unsupported version.');
  }
  return {
    qdrant: {
      url: bundle.qdrant.url,
      apiKey: bundle.qdrant.apiKey ?? '',
      collectionPrefix: bundle.qdrant.collectionPrefix ?? '',
    },
    gemini: { apiKeys: geminiKeys },
    llm: { baseUrl: bundle.llm.baseUrl, apiKeys: llmKeys, model: bundle.llm.model },
  };
}
