name: workspacegpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - requests
  - numpy
  - pydantic
  - faiss-cpu
  - pip:
    - transformers
    - sentence-transformers
    - streamlit
    - langchain
    - langchain-core
    - langchain-text-splitters
    - langchain-community
    - langchain-ollama
    - langchain-huggingface
    - watchdog
    - fastapi
    - uvicorn
    - asyncio
    - starlette
